name: Release

on:
  workflow_run:
    workflows: ["Build"] 
    types: [completed]
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: 'test | staging | prod'
        default: 'test'
        type: choice
        options:
          - test
          - staging
          - prod
      components:
        required: false
        description: 'Optional: Comma-separated list of components to deploy. Leave empty to use components from build artifacts'
        default: ''
      run_id:
        required: true
        description: 'Run ID of the build workflow'
      runner_label:
        required: false
        description: 'Runner label (default: ubuntu-latest, or use self-hosted)'
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - self-hosted

jobs:
  release:
    uses: Blinc-Technologies/workflow-templates/.github/workflows/release.yml@main
    with:
      environment: ${{ inputs.environment }}
      components: ${{ inputs.components }}
      run_id: ${{ inputs.run_id }}
      trigger_type: ${{ github.event_name }}
      workflow_run_id: ${{ github.event.workflow_run.id }}
      workflow_run_conclusion: ${{ github.event.workflow_run.conclusion }}
      workflow_run_branch: ${{ github.event.workflow_run.head_branch }}
      project_name: ${{ vars.PROJECT_NAME }}
      namespace: ${{ vars.NAMESPACE }}
      secret_store_name: ${{ vars.SECRET_STORE_NAME }}
      runner_label: ${{ github.event.inputs.runner_label}}
    secrets:
      gh_actions_token: ${{ secrets.GH_ACTIONS_TOKEN }}
      gh_gitops_token: ${{ secrets.GH_ACTIONS_TOKEN }}