name: Build

on:
  push:
    branches: 
      - main
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: 'test | staging | prod'
        default: 'test'
        type: choice
        options:
          - test
          - staging
          - prod
      release_mode:
        required: false
        description: 'Release mode'
        default: 'false'
        type: choice
        options:
          - 'false'
          - build_only
          - build_and_deploy
      components_to_build:
        required: false
        description: 'Optional: component(s) to build. Leave empty to use default vars.COMPONENTS_TO_BUILD'
        default: '' 
      runner_label:
        required: false
        description: 'Runner label (default: ubuntu-latest, or use self-hosted)'
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - self-hosted

jobs:
  build:
    uses: Blinc-Technologies/workflow-templates/.github/workflows/build.yml@main
    with:
      project_name: ${{ vars.PROJECT_NAME }}
      components_to_build: >-
        ${{ github.event.inputs.components_to_build != '' 
            && github.event.inputs.components_to_build 
            || vars.COMPONENTS_TO_BUILD }}
      create_release: ${{ github.event.inputs.release_mode }}
      environment: ${{ github.event.inputs.environment }}
      runner_label: ${{ github.event.inputs.runner_label}}